version: '3.3'
services:
    mongo:
        image: mongo:4.2.0-bionic
        hostname: "mongo"
        restart: always
        labels:
            NAME: "mongo"
        networks:
            - iot-labs
    mongo-express:
        image: mongo-express:0.49.0
        hostname: "mongo_express"
        restart: always
        ports:
            - 8081:8081
        environment:
             ME_CONFIG_MONGODB_SERVER: mongo
        labels:
            NAME: "mongo_express"
        networks:
            - iot-labs
networks:
    iot-labs:
        external: true
